"""Remove legacy columns from Direction and finalize schema

Revision ID: 7e821dc4bbf5
Revises: e90691806c21
Create Date: 2026-01-17 16:15:08.324880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e821dc4bbf5'
down_revision = 'e90691806c21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.drop_column('semester')
        batch_op.drop_column('enrollment_year')
        batch_op.drop_column('education_type')
        batch_op.drop_column('course_year')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_year', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('education_type', sa.VARCHAR(length=20), server_default=sa.text("'kunduzgi'"), nullable=False))
        batch_op.add_column(sa.Column('enrollment_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('semester', sa.INTEGER(), server_default=sa.text('1'), nullable=True))

    # ### end Alembic commands ###
