"""Initial migration with schema changes

Revision ID: e90691806c21
Revises: 
Create Date: 2026-01-17 16:02:02.150864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e90691806c21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('direction_group')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.alter_column('max_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_assignment_direction', 'direction', ['direction_id'], ['id'])

    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        # Postpone dropping columns until data is migrated
        # batch_op.drop_column('enrollment_year')
        # batch_op.drop_column('semester')
        # batch_op.drop_column('education_type')
        # batch_op.drop_column('course_year')

    with op.batch_alter_table('grade_scale', schema=None) as batch_op:
        batch_op.alter_column('min_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('max_score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True)) # Temporarily nullable
        batch_op.add_column(sa.Column('enrollment_year', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_group_direction', 'direction', ['direction_id'], ['id'])

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_lesson_group_id'))
        batch_op.create_foreign_key('fk_lesson_group', 'group', ['group_id'], ['id'])

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('room')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('faculty_id')

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_unique_constraint('uq_user_login', ['login'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('submission', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'faculty', ['faculty_id'], ['id'])
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_lesson_group_id'), ['group_id'], unique=False)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('enrollment_year')
        batch_op.drop_column('semester')

    with op.batch_alter_table('grade_scale', schema=None) as batch_op:
        batch_op.alter_column('max_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('min_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('direction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_year', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('education_type', sa.VARCHAR(length=20), server_default=sa.text("'kunduzgi'"), nullable=False))
        batch_op.add_column(sa.Column('semester', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
        batch_op.add_column(sa.Column('enrollment_year', sa.INTEGER(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('max_score',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    op.create_table('direction_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('direction_id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    # ### end Alembic commands ###
